server:
  ip: 0.0.0.0
  port: 1323
  runMode: debug
  static: static/
database:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbName: go_cmdb
  tablePrefix: tb_
  debug: false
email:
  username: xxx
  password: ""
  host: mail.xxx.com
  receiver:
    - xxx.xxx.com
  senderEmail: xxx.com
  subject: "go-cmdb"
log:
  level: 5  # debug
  output: "logs/app.log"